[package]
name = "nma_command"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.68"
nma_models = { path = "../../nma_models"}
proc-macro2 = "1.0.86"

